class CurrencyData {
  CurrencyData({
    required this.code,
    required this.name,
    required this.timestamp,
    required this.rate,
  }) : symbol = _currencySymbols[code] ?? code;

  final String code;
  final String name;
  final int timestamp;
  final double rate;
  final String symbol;

  static const _currencySymbols = <String, String>{
    'AED': 'د.إ',
    'AFN': '؋',
    'ALL': 'L',
    'AMD': '֏',
    'ANG': 'ƒ',
    'AOA': 'Kz',
    'ARS': r'$',
    'AUD': r'A$',
    'AWG': 'ƒ',
    'AZN': '₼',
    'BAM': 'KM',
    'BBD': r'Bds$',
    'BDT': '৳',
    'BGN': 'лв',
    'BHD': '.د.ب',
    'BIF': 'Fr',
    'BMD': r'$',
    'BND': r'B$',
    'BOB': 'Bs.',
    'BRL': r'R$',
    'BSD': r'B$',
    'BTC': '₿',
    'BTN': 'Nu',
    'BWP': 'P',
    'BYN': 'Br',
    'BYR': 'Br',
    'BZD': r'BZ$',
    'CAD': r'CA$',
    'CDF': 'Fr',
    'CHF': 'Fr',
    'CLF': 'UF',
    'CLP': r'$',
    'CNY': '¥',
    'CNH': '¥',
    'COP': r'$',
    'CRC': '₡',
    'CUC': r'$',
    'CUP': r'$',
    'CVE': r'$',
    'CZK': 'Kč',
    'DJF': 'Fr',
    'DKK': 'kr',
    'DOP': r'RD$',
    'DZD': 'د.ج',
    'EGP': '£',
    'ERN': 'Nfk',
    'ETB': 'Br',
    'EUR': '€',
    'FJD': r'FJ$',
    'FKP': '£',
    'GBP': '£',
    'GEL': '₾',
    'GGP': '£',
    'GHS': '₵',
    'GIP': '£',
    'GMD': 'D',
    'GNF': 'Fr',
    'GTQ': 'Q',
    'GYD': r'G$',
    'HKD': r'HK$',
    'HNL': 'L',
    'HRK': 'kn',
    'HTG': 'G',
    'HUF': 'Ft',
    'IDR': 'Rp',
    'ILS': '₪',
    'IMP': '£',
    'INR': '₹',
    'IQD': 'ع.د',
    'IRR': '﷼',
    'ISK': 'kr',
    'JEP': '£',
    'JMD': r'J$',
    'JOD': 'JD',
    'JPY': '¥',
    'KES': 'KSh',
    'KGS': 'лв',
    'KHR': '៛',
    'KMF': 'Fr',
    'KPW': '₩',
    'KRW': '₩',
    'KWD': 'د.ك',
    'KYD': r'CI$',
    'KZT': '₸',
    'LAK': '₭',
    'LBP': 'ل.ل',
    'LKR': '₨',
    'LRD': r'L$',
    'LSL': 'L',
    'LTL': 'Lt',
    'LVL': 'Ls',
    'LYD': 'ل.د',
    'MAD': 'د.م.',
    'MDL': 'L',
    'MGA': 'Ar',
    'MKD': 'ден',
    'MMK': 'K',
    'MNT': '₮',
    'MOP': 'P',
    'MRU': 'UM',
    'MUR': '₨',
    'MVR': 'Rf',
    'MWK': 'MK',
    'MXN': r'MX$',
    'MYR': 'RM',
    'MZN': 'MT',
    'NAD': r'N$',
    'NGN': '₦',
    'NIO': r'C$',
    'NOK': 'kr',
    'NPR': '₨',
    'NZD': r'NZ$',
    'OMR': '﷼',
    'PAB': 'B/.',
    'PEN': 'S/.',
    'PGK': 'K',
    'PHP': '₱',
    'PKR': '₨',
    'PLN': 'zł',
    'PYG': '₲',
    'QAR': '﷼',
    'RON': 'lei',
    'RSD': 'din',
    'RUB': '₽',
    'RWF': 'Fr',
    'SAR': '﷼',
    'SBD': r'SI$',
    'SCR': '₨',
    'SDG': '£',
    'SEK': 'kr',
    'SGD': r'S$',
    'SHP': '£',
    'SLE': 'Le',
    'SLL': 'Le',
    'SOS': 'Sh',
    'SRD': r'$',
    'STD': 'Db',
    'STN': 'Db',
    'SVC': '₡',
    'SYP': '£',
    'SZL': 'L',
    'THB': '฿',
    'TJS': 'SM',
    'TMT': 'T',
    'TND': 'د.ت',
    'TOP': r'T$',
    'TRY': '₺',
    'TTD': r'TT$',
    'TWD': r'NT$',
    'TZS': 'Sh',
    'UAH': '₴',
    'UGX': 'Sh',
    'USD': r'$',
    'UYU': r'$U',
    'UZS': 'лв',
    'VES': 'Bs.S',
    'VND': '₫',
    'VUV': 'Vt',
    'WST': 'T',
    'XAF': 'Fr',
    'XAG': 'oz t',
    'XAU': 'oz t',
    'XCD': r'EC$',
    'XCG': 'ƒ',
    'XDR': 'SDR',
    'XOF': 'Fr',
    'XPF': 'Fr',
    'YER': '﷼',
    'ZAR': 'R',
    'ZMK': 'ZK',
    'ZMW': 'ZK',
    'ZWL': r'$'
};

  static String symbolFor(String code) => _currencySymbols[code] ?? code;
}

extension NumAmountExt on num? {
  String get formatSum {
    if (this == null) return '';
    final value = this!.toDouble();
    final fixed = value.toStringAsFixed(2);
    final parts = fixed.split('.');
    var integerPart = parts[0];
    final decimalPart = parts.length > 1 ? parts[1] : '00';

    final isNegative = integerPart.startsWith('-');
    if (isNegative) integerPart = integerPart.substring(1);
    final buffer = StringBuffer();
    for (var i = 0; i < integerPart.length; i++) {
      if (i > 0 && (integerPart.length - i) % 3 == 0) buffer.write(',');
      buffer.write(integerPart[i]);
    }
    integerPart = buffer.toString();

    if (integerPart.length == 1) integerPart = '0$integerPart';

    return '${isNegative ? '-' : ''}$integerPart.$decimalPart';
  }
}
